"""renamed in file type enum

Revision ID: 14cf4e103904
Revises: 476bef469cd0
Create Date: 2026-09-25 01:08:05.291466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '14cf4e103904'
down_revision: Union[str, Sequence[str], None] = '476bef469cd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='filetype',
        new_values=['audio', 'cover'],
        affected_columns=[TableReference(table_schema='public', table_name='files', column_name='file_type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='filetype',
        new_values=['sound', 'image'],
        affected_columns=[TableReference(table_schema='public', table_name='files', column_name='file_type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
