"""cascade del file

Revision ID: 27e5758777ab
Revises: 294d9efdeab8
Create Date: 2025-09-04 22:23:40.358135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27e5758777ab'
down_revision: Union[str, Sequence[str], None] = '294d9efdeab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('files_soundtrack_id_fkey'), 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'soundtracks', ['soundtrack_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key(op.f('files_soundtrack_id_fkey'), 'files', 'soundtracks', ['soundtrack_id'], ['id'])
    # ### end Alembic commands ###
