"""file metadata

Revision ID: 2c965053c1d8
Revises: cd538795f97e
Create Date: 2025-08-22 20:48:20.710069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c965053c1d8'
down_revision: Union[str, Sequence[str], None] = 'cd538795f97e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('sound', 'image', name='filetype').create(op.get_bind())
    op.create_table('files',
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('soundtrack_id', sa.Integer(), nullable=False),
    sa.Column('file_type', postgresql.ENUM('sound', 'image', name='filetype', create_type=False), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['soundtrack_id'], ['soundtracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    sa.Enum('sound', 'image', name='filetype').drop(op.get_bind())
    # ### end Alembic commands ###
