"""track duration in file model

Revision ID: 476bef469cd0
Revises: ad6e356ad099
Create Date: 2026-06-28 14:04:19.644126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '476bef469cd0'
down_revision: Union[str, Sequence[str], None] = 'ad6e356ad099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('duration', sa.Integer(), nullable=True))
    op.drop_column('soundtracks', 'track_length')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soundtracks', sa.Column('track_length', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('files', 'duration')
    # ### end Alembic commands ###
