"""username -> login

Revision ID: 5cc66f4b9301
Revises: 2c965053c1d8
Create Date: 2025-08-23 00:53:34.511474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cc66f4b9301'
down_revision: Union[str, Sequence[str], None] = '2c965053c1d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.drop_constraint(op.f('users_login_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'login')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_login_key'), 'users', ['login'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
