"""storage filename

Revision ID: 6adda95a7231
Revises: 5cc66f4b9301
Create Date: 2025-09-03 00:17:30.623062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6adda95a7231'
down_revision: Union[str, Sequence[str], None] = '5cc66f4b9301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('storage_filename', sa.String(), nullable=False))
    op.add_column('files', sa.Column('original_filename', sa.String(), nullable=False))
    op.drop_column('files', 'filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('files', 'original_filename')
    op.drop_column('files', 'storage_filename')
    # ### end Alembic commands ###
