"""track listens removed

Revision ID: ad6e356ad099
Revises: 27e5758777ab
Create Date: 2026-06-28 01:48:47.645462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad6e356ad099'
down_revision: Union[str, Sequence[str], None] = '27e5758777ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('soundtracks', 'listens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soundtracks', sa.Column('listens', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
